name: First Test on AWS
# it Trigers when you push on branch.
on :
  push:
    branch:
      - main


jobs:

  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4 # some of inbuilt functions, provided by github.com creats a copy of files.

      - name: Install Python-3     # after creating copy we will install dependencies and liberaries.
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      




    
